apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-app
  template:
    metadata:
      labels:
        app: qr-app
    spec:
      containers:
      - name: qr-app
        image: docker.io/votre-nom-dutilisateur/qr-app  # Remplacé dynamiquement
        ports:
          - containerPort: 5000