name: Build and Test QR API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: qr_secure
          MYSQL_USER: qr_user
          MYSQL_PASSWORD: qr_password
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --name db

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h db -u qr_user -pqr_password --silent; then
              echo "✅ MySQL is up!"
              break
            fi
            echo "⏳ Waiting for MySQL..."
            sleep 2
          done

      - name: Run tests
        env:
          DATABASE_URI: mysql+pymysql://qr_user:qr_password@db/qr_secure
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python your_test_script_or_run.py
