name: Build, Test, Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io                  # Docker Hub (registre Docker)
  IMAGE_NAME: oualibaleh/qr-app     # Nom de l'image Docker
  TAG: ${{ github.sha }}               # Tag basé sur le hash de commit

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      # Étape 3 : Lancer Docker Compose (si utilisé)
      - name: Start Docker containers
        run: docker compose up -d --build

      # Étape 4 : Attendre MySQL (si utilisé dans Docker Compose)
      - name: Wait for MySQL
        run: |
          echo "⏳ Waiting for MySQL..."
          for i in {1..30}; do
            if docker exec $(docker ps -qf "name=db") mysqladmin ping -h localhost -u qr_user -pqr_password --silent; then
              echo "✅ MySQL OK"
              break
            fi
            sleep 2
          done

      # Étape 5 : Attendre l'API (si utilisée dans Docker Compose)
      - name: Wait for API
        run: |
          echo "⏳ Waiting for API..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:5000; then
              echo "✅ API OK"
              break
            fi
            sleep 2
          done
      
        # Ajouter cette étape avant l'installation des dépendances Python
      - name: Install MySQL dependencies
        run: |
              sudo apt-get update
              sudo apt-get install -y python3-dev default-libmysqlclient-dev gcc pkg-config libzbar0

      # Étape 6 : Installer les dépendances
      - name: Install Python dependencies
        run: |
          pip install requests pyzbar cryptography pillow

      # Étape 7 : Exécuter les tests
      - name: Run integration tests
        run: |
          python tests/integration/test_ouali.py

      # Étape 8 : Arrêter les containers
      - name: Cleanup
        run: docker compose down

  deploy-to-docker-hub:
    needs: build-and-test                 # Dépend du job build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'    # Déploie seulement sur la branche main

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 4 : Pousser l'image sur Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      # Étape 5 : Optionnel (Exécuter l'image dans un container Docker sur un serveur)
      # - name: Run Docker container (si nécessaire)
      #   run: |
      #     docker run -d --name my-app ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
