name: Build and Test QR API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 👇 Nouvelle étape pour installer docker-compose-plugin
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and start Docker containers
        run: |
          docker compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "⏳ Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if docker exec $(docker ps -qf "name=db") mysqladmin ping -h localhost -u qr_user -pqr_password --silent; then
              echo "✅ MySQL is up!"
              break
            fi
            sleep 2
          done

      - name: Wait for API to be ready
        run: |
          echo "⏳ Waiting for API to be ready..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:5000; then
              echo "✅ API is up!"
              break
            fi
            sleep 2
          done

      - name: Install Python dependencies
        run: |
          pip install requests pyzbar cryptography pillow

      - name: Run integration tests
        run: |
          python tests/integration/test_ouali.py

      - name: Stop and remove containers
        run: |
          docker compose down
