name: Build and Test QR API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker (Docker est déjà installé sur ubuntu-latest)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build et lancer docker-compose
      - name: Build and start Docker containers
        run: |
          docker-compose up -d --build

      # 4. Attendre que MySQL soit prêt
      - name: Wait for MySQL to be ready
        run: |
          echo "⏳ Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if docker exec $(docker ps -qf "name=db") mysqladmin ping -h localhost -u qr_user -pqr_password --silent; then
              echo "✅ MySQL is up!"
              break
            fi
            sleep 2
          done

      # 5. Attendre que l'API soit prête
      - name: Wait for API to be ready
        run: |
          echo "⏳ Waiting for API to be ready..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:5000; then
              echo "✅ API is up!"
              break
            fi
            sleep 2
          done

      # 6. Installer les dépendances pour les tests (requests + pyzbar + cryptography...)
      - name: Install Python dependencies
        run: |
          pip install requests pyzbar cryptography pillow

      # 7. Lancer les tests d'intégration
      - name: Run integration tests
        run: |
          python tests/integration/test_ouali.py

      # 8. Nettoyer les conteneurs
      - name: Stop and remove containers
        run: |
          docker-compose down
