name: Build and Test QR API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      # Étape 3 : Construire et démarrer les containers Docker
      - name: Build and start Docker containers
        run: |
          docker compose up -d --build

      # Étape 4 : Attendre que MySQL soit prêt
      - name: Wait for MySQL to be ready
        run: |
          echo "⏳ Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if docker exec $(docker ps -qf "name=db") mysqladmin ping -h localhost -u qr_user -pqr_password --silent; then
              echo "✅ MySQL is up!"
              break
            fi
            sleep 2
          done

      # Étape 5 : Attendre que l'API soit prête
      - name: Wait for API to be ready
        run: |
          echo "⏳ Waiting for API to be ready..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:5000; then
              echo "✅ API is up!"
              break
            fi
            sleep 2
          done

      # Étape 6 : Installer les dépendances Python
      - name: Install Python dependencies
        run: |
          pip install requests pyzbar cryptography pillow

      # Étape 7 : Définir PYTHONPATH pour que 'decryptor' soit trouvé
      - name: Set PYTHONPATH
        run: export PYTHONPATH=$PYTHONPATH:$(pwd)

      # Étape 8 : Exécuter les tests d'intégration
      - name: Run integration tests
        run: |
          python tests/integration/test_ouali.py

      # Étape 9 : Arrêter et supprimer les containers Docker
      - name: Stop and remove containers
        run: |
          docker compose down
